print("############################## \n")
print("#                            # \n")
print("#    Nabilla Putri Nugraha   # \n")
print("#        2410817220009       # \n")
print("#                            # \n")
print("############################## ")